---

- name: Install nginx
  apt: pkg=nginx state=present

- name: Copy nginx confing
  template: src={{nginx_conf_template}} dest=/etc/nginx/sites-available/{{nginx_config_name}}
  notify: reload nginx

- name: Enable site
  file: src=/etc/nginx/sites-available/{{nginx_config_name}} path=/etc/nginx/sites-enabled/{{nginx_config_name}} state=link
  notify: reload nginx

- name: Remove default nginx config
  file: path=/etc/nginx/sites-enabled/default state=absent
  notify: reload nginx

#- name: set up a test html page
#  shell: mkdir -p /var/www/{{inventory_hostname}} && echo "Hello Nginx" > /var/www/{{inventory_hostname}}/index.html

#- name: set up a test php page
#  shell: mkdir -p /var/www/{{inventory_hostname}} && echo "<?php phpinfo();" > /var/www/{{inventory_hostname}}/index.php
