---

git_user_name: git
git_user_group: www-data
git_user_home: /var/git
git_user_createhome: true
git_user_shell: /usr/bin/git-shell

# ключ чтобы заливать с локальной машины (git push origin master)
git_authorized_key: ""

# read-only key для Bitbucket или GitHub, чтобы получить доступ к
# репозиторию для скачивания файлов (деплоя на сервер из удаленного репозитория)
git_deployment_key: ""

git_remote: ""

