---

- name: Build project (composer install, migrate, webpack, gulp)
  become: true
  become_user: git
  shell: "{{item}}"
  args:
    chdir: /var/www/{{inventory_hostname}}
  with_items:
    - composer install
    - composer dump-autoload

- name: Setup laravel storage permissions
  file: path=/var/www/{{inventory_hostname}}/storage mode=0775 recurse=true

- name: Setup laravel bootstrap permissions
  file: path=/var/www/{{inventory_hostname}}/bootstrap/cache mode=0775 recurse=true
