---
# ansible-playbook -i inventory/hosts sites/site-laravel.yml

- hosts: site
  roles:
    - role: nginx
      nginx_conf_template: laravel.conf.j2
    - role: php
    - role: git
    - role: mysql
      mysql_databases:
        - name: maverickretailers
    - role: dotenv
      dotenv_vars:
          APP_NAME=Laravel
          APP_ENV=local
          APP_KEY=base64:AJwk7b7ceZFH/4aY62Vvan9oUd3G7ZbGknvEFSteHds=
          APP_DEBUG=true
          APP_LOG_LEVEL=debug
          APP_URL=http://{{inventory_hostname}}

          DB_CONNECTION=mysql
          DB_HOST=127.0.0.1
          DB_PORT=3306
          DB_DATABASE=homestead
          DB_USERNAME=homestead
          DB_PASSWORD=secret

          BROADCAST_DRIVER=log
          CACHE_DRIVER=file
          SESSION_DRIVER=file
          QUEUE_DRIVER=sync

          REDIS_HOST=127.0.0.1
          REDIS_PASSWORD=null
          REDIS_PORT=6379

          MAIL_DRIVER=smtp
          MAIL_HOST=smtp.mailtrap.io
          MAIL_PORT=2525
          MAIL_USERNAME=null
          MAIL_PASSWORD=null
          MAIL_ENCRYPTION=null
    - role: laravel
