---
# ansible-playbook -i inventory/hosts sites/site-opencart.yml

- hosts: site
  roles:
    - role: nginx
      nginx_conf_template: php.conf.j2
    - role: php
    - role: git
    - role: mysql
      mysql_databases:
        - name: opencart
    - role: opencart
