---

- name: Adding primary group
  group: name="{{item}}" state=present
  when: user_groups is defined
  with_items: "{{user_groups|default()}}"

- name: Adding users
  user:
    name: "{{item.name}}"
    system: "{{item.system|default(omit)}}"
    group: "{{item.group|default(omit)}}"
    groups: "{{item.groups|default(omit)}}"
    password: "{{item.password|default(omit)}}"
    createhome: "{{item.createhome|default(omit)}}"
    home: "{{item.home|default(omit)}}"
    shell: "{{item.shell|default(omit)}}"
#    update_password: true
  with_items: "{{users}}"

- name: Adding user's authorized keys
  authorized_key:
    user: "{{item.name}}"
    key: "{{lookup('file', item.authorized_key)}}"
  when: item.key is defined
  with_items:
    - "{{users}}"

- name: Creating ssh keys for user {{item.name}}
  copy: src={{item.key}} dest={{item.home}}/.ssh/id_rsa owner={{item.name}} group={{item.group}} mode=0600
  with_items: "{{users}}"

- name: Creating ssh keys for user {{item.name}}
  copy: src={{item.key}}.pub dest={{item.home}}/.ssh/id_rsa.pub owner={{item.name}} group={{item.group}} mode=0644
  with_items: "{{users}}"
