# https://yarnpkg.com/lang/en/docs/install/#debian-stable

- name: Istall curl
  apt:
    name: curl
    update_cache: yes

- name: Fetch Yarn pubkey
  shell: curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -

- name: Add Yarn sources
  apt_repository:
    repo: deb https://dl.yarnpkg.com/debian/ stable main
    filename: yarn
    state: present

#- name: Add Yarn sources
#  shell: echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list

- name: Update repositories cache and install "yarn" package
  apt:
    name: yarn
    update_cache: yes
