---

- name: Install the gpg key for nodejs LTS
  apt_key:
    url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
    state: present

- name: Install the nodejs LTS repos
  apt_repository:
    repo: "deb https://deb.nodesource.com/node_6.x {{ ansible_distribution_release }} main"
    state: present
    update_cache: yes

- name: Install the nodejs
  apt:
    name: nodejs
    state: present

- name: Setup node service
  template: src=node.service.j2 dest=/etc/systemd/system/node.service
  tags: node_setup_service

#- name: Enable node service
#  service:
#    name: node
#    state: started

#- name: Update npm
#  npm: name=npm state=latest global=yes

#- name: Start node service
#  service: name=node state=started
