---
# ansible-playbook -i inventory/hosts sites/dafisha.yml --tags="node"

- import_playbook: ../bootstrap.yml

- hosts: site
  vars:
    local_root_path: "/Users/extg/Workspaces/dafisha/dafisha.ru"

  roles:
    - role: swap
      tags:
        - swap

    - role: git
      git_deployment_key: "/Users/extg/Workspaces/dafisha/dafisha.ru/credentials/dafisha_deployment_key"
      git_remote: "git@bitbucket.org:dafisha/dafisha.ru.git"
      git_key_file: "{{ansible_env.HOME}}/.ssh/id_rsa"
      git_authorized_key: "~/.ssh/id_rsa.pub"
      tags:
        - git
        - dafisha-api
        - dafisha-main
        - dafisha-admin

    - role: nginx
      nginx_conf_template: node.conf.j2
      nginx_node_port: 8080
      nginx_root: "/var/www/{{inventory_hostname}}/packages/dafisha-api"
      nginx_server_name: "api.dafisha.ru"
      nginx_config_name: "api.dafisha.ru.conf"
      tags:
        - nginx
        - dafisha-api

    - role: nginx
      nginx_conf_template: node.conf.j2
      nginx_node_port: 8081
      nginx_root: "/var/www/{{inventory_hostname}}/packages/dafisha-main"
      nginx_server_name: "dafisha.ru"
      nginx_config_name: "dafisha.ru.conf"
      tags:
        - nginx
        - dafisha-main

    - role: nginx
      nginx_conf_template: node.conf.j2
      nginx_node_port: 8082
      nginx_root: "/var/www/{{inventory_hostname}}/packages/dafisha-admin"
      nginx_server_name: "admin.dafisha.ru default"
      nginx_config_name: "admin.dafisha.ru.conf"
      tags:
        - nginx
        - dafisha-admin

    - role: node
      node_service_name: dafisha-main-node
      node_working_directory: "/var/www/{{inventory_hostname}}/packages/dafisha-main"
      node_start_file: server.js
      node_syslog_identifier: node.dafisha
      tags:
        - node
        - dafisha-main

    - role: node
      node_service_name: dafisha-api-node
      node_working_directory: "/var/www/{{inventory_hostname}}/packages/dafisha-api"
      node_start_file: server.js
      node_syslog_identifier: node.dafisha
      tags:
        - node
        - dafisha-api

    - role: node
      node_service_name: dafisha-admin-node
      node_working_directory: "/var/www/{{inventory_hostname}}/packages/dafisha-admin"
      node_start_file: server.js
      node_syslog_identifier: node.dafisha
      tags:
        - node
        - dafisha-admin

    - role: redis
      tags:
        - redis

    - role: yarn
      tags:
        - yarn

  tasks:
    - name: Install "lerna" npm package globally
      npm:
        name: lerna
        global: yes
